name: Rust CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        container:
            image: rust:1.90
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - name: Run checks
              run: ./bolt.sh check

    build:
        name: Build
        runs-on: ubuntu-latest
        container:
            image: rust:1.90
        needs: check
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - name: Build
              run: ./bolt.sh build

    test:
        name: Test
        runs-on: ubuntu-latest
        container:
            image: rust:1.90
        needs: build
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - name: Install cargo-nextest
              shell: bash
              run: cargo install cargo-nextest --locked

            - name: Run tests
              run: ./bolt.sh test
